AWSTemplateFormatVersion: 2010-09-09
Description: cloud9 stack
# stack에서 사용할 파라미터 정의.
Parameters:
  AppName:
    Type: String
    Description: Name of the application.
# CLI 명령어에서 파라미터를 반드시 넣어야 함. ex) --parameter-overrides AppName=serverless-hands-on
  InstanctType: 
    Type: String
    Description: ec2 instance type
    Default: t2.micro
# CLI 명령어에서 파라미터를 넣지 않으면 Default 값이 적용
Resources:
# 스택 내부에서 사용할 리소스 이름
  Cloud9:
# 리소스 타입  
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
# Cloud9 리소스의 이름    
      Name: !Ref AWS::StackName
# N분 동안 사용하지 않으면 EC2 instance를 Stop
      AutomaticStopTimeMinutes: 60
# Cloud9에서 사용할 EC2 instance type
      InstanceType: !Ref InstanctType
      